"""DeepEyesV2 model wrapper — Qwen2.5-VL with agentic tool-use CoT.

DeepEyesV2 (honglyhly/DeepEyesV2_7B_1031) is a Qwen2.5-VL-7B model
fine-tuned via SFT + GRPO reinforcement learning to perform multi-turn
reasoning using a Python code-execution tool.

The model's reasoning loop:
1. Receives system prompt + image + user query.
2. Optionally executes Python code (``<code>...</code>``) to inspect the image.
3. Repeats until it emits ``<answer>...</answer>``, which terminates the loop.

This module exposes:
- :class:`DeepEyesV2Model` — ``BaseVisualCoTModel`` implementation.
- :func:`_parse_answer` — extract ``<answer>`` tag content.
- :func:`_extract_code_block` — extract ``<code>`` tag content.
- :func:`_execute_code` — run Python code with an isolated namespace.
"""

from __future__ import annotations

import base64
import contextlib
import io
import os
import re
from typing import Any, Dict, List, Optional

# Force a non-interactive matplotlib backend before any user code can import
# matplotlib.  Without this, plt.show() inside the code sandbox opens a GUI
# window and blocks execution indefinitely.
os.environ.setdefault("MPLBACKEND", "Agg")

import torch
from PIL import Image

from src.models.base import BaseVisualCoTModel
from src.utils.logging import get_logger

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_MODEL_ID = "honglyhly/DeepEyesV2_7B_1031"
DEFAULT_MAX_TURNS = 10

# ---------------------------------------------------------------------------
# Exact prompts from the paper (Appendix A.8 of arXiv:2511.05271).
# Search-tool instructions are omitted; only the Python-code tool is kept.
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are an agent - please keep going until the user's query is completely resolved, before \
ending your turn and yielding back to the user. Only terminate your turn when you are sure \
that the problem is solved.

Solve the following problem step by step. In your reasoning process, if the answer cannot be \
determined, you can write Python code in a Jupyter Notebook to process the image and extract \
more information from it. The stdout and stderr content, along with the images generated by \
"plt.show()" will be returned to better assist with the user query.

You MUST use the python tool to analyze or transform images whenever it could improve your \
understanding. This includes but is not limited to zooming in, rotating, adjusting contrast, \
computing statistics, or isolating features.

You MUST plan extensively before each function call, and reflect extensively on the outcomes \
of the previous function calls. DO NOT do this entire process by making function calls only, \
as this can impair your ability to solve the problem and think insightfully.

For all the provided images, in order, the i-th image has already been read into the global \
variable "image_i" using the "PIL.Image.open()" function. For example, the first image can \
be accessed as "image_1". When writing Python code, you can directly use these variables \
without needing to read them again.

## Tools

## python
Your python code should be enclosed within <code> </code> tag.
Example for calling Python code in Jupyter Notebook:
<code>
'''python
# python code here
'''
</code>

Note:
1. python can be called to analyze the image. python will respond with the output of the \
execution or time out after 300.0 seconds.
2. Like jupyter notebook, you can use Python code to process the input image and use \
"plt.show()" to visualize processed images in your code.
3. All python code are running in the same jupyter notebook kernel, which means the \
functions and variables are automatically stored after code execution.
4. You program should always returns in finite time. Do not write infinite loop in your code.
5. Writing file to disk is not allowed.
"""

# USER_PROMPT_TEMPLATE: wraps each user query.
# This is the exact per-question template from the paper — it is what instructs
# the model to emit <answer> tags and use the <think>/<code>/<answer> format.
USER_PROMPT_TEMPLATE = """\
{question}

You must put your answer inside <answer> </answer> tags, i.e., <answer> answer here </answer>.
Please reason step by step. Use Python code to process the image if necessary.

Format strictly as <think> </think> <code> </code> (if code is needed)
or <think> </think> <answer> </answer> (if answer is ready).
"""

# RETURN_CODE_USER_PROMPT: exact template injected after each code execution.
# Triple-quote delimiters are on their own lines, exactly as in the paper.
RETURN_CODE_USER_PROMPT = """\
Code execution result:
stdout:
'''
{stdout}
'''
stderr:
'''
{stderr}
'''
Image:
"""

# ---------------------------------------------------------------------------
# Module-level helpers (public for testability)
# ---------------------------------------------------------------------------

_ANSWER_RE = re.compile(r"<answer>(.*?)</answer>", re.DOTALL)
_CODE_RE = re.compile(r"<code>(.*?)</code>", re.DOTALL)
# Matches the '''python ... ''' wrapper the model places inside <code> tags.
_PYTHON_TRIPLE_QUOTE_RE = re.compile(r"^\s*'''python\s*\n(.*?)\n\s*'''\s*$", re.DOTALL)
# Backtick fence *inside* a <code> tag: ```python ... ```
_BACKTICK_FENCE_RE = re.compile(r"^\s*```python\s*\n(.*?)\n\s*```\s*$", re.DOTALL)
# Top-level bare backtick fence (model output without <code> wrapper).
_BARE_FENCE_RE = re.compile(r"```python\s*\n(.*?)\n```", re.DOTALL)


def _parse_answer(text: str) -> Optional[str]:
    """Extract the first ``<answer>...</answer>`` span, stripped, or ``None``.

    Args:
        text: Raw model output string.

    Returns:
        Stripped answer text, or ``None`` if no ``<answer>`` tag is found.
    """
    m = _ANSWER_RE.search(text)
    return m.group(1).strip() if m else None


def _extract_code_block(text: str) -> Optional[str]:
    """Extract the first ``<code>...</code>`` span, stripping any Python markdown wrapper.

    The model wraps code in a ``'''python ... '''`` (or `` ```python ... ``` ``) fence
    *inside* the ``<code>`` tag.  Returning that wrapper verbatim to ``exec()`` would
    make the code a silent no-op (Python evaluates it as a string literal).  We strip
    the wrapper so the caller receives executable Python.

    Args:
        text: Raw model output string.

    Returns:
        Executable Python source (indentation preserved), or ``None`` if no tag found.
    """
    # Priority 1: explicit <code>...</code> tags (training format).
    m = _CODE_RE.search(text)
    if m:
        raw = m.group(1)
        for pattern in (_PYTHON_TRIPLE_QUOTE_RE, _BACKTICK_FENCE_RE):
            wrapper_m = pattern.match(raw)
            if wrapper_m:
                return wrapper_m.group(1)
        return raw
    # Priority 2: bare ```python ... ``` fence (model's fallback output format).
    bare_m = _BARE_FENCE_RE.search(text)
    if bare_m:
        return bare_m.group(1)
    return None


def _execute_code(code: str, namespace: Dict[str, Any]) -> str:
    """Execute *code* in *namespace* and return captured stdout or error info.

    Args:
        code: Python source code to execute.
        namespace: Execution namespace; modified in-place by the code.

    Returns:
        Captured stdout (trailing newlines stripped), or an error summary
        of the form ``"ExceptionType: message"`` on failure.
    """
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            exec(code, namespace)  # noqa: S102
    except Exception as exc:  # noqa: BLE001
        return f"{type(exc).__name__}: {exc}"
    return buf.getvalue().rstrip("\n")


# ---------------------------------------------------------------------------
# Model class
# ---------------------------------------------------------------------------


class DeepEyesV2Model(BaseVisualCoTModel):
    """Multi-turn agentic Visual CoT model backed by DeepEyesV2 / Qwen2.5-VL.

    Loads ``Qwen2VLForConditionalGeneration`` weights lazily on the first
    :meth:`generate` call (no download at import time).

    Args:
        model_id: HuggingFace model ID or local checkpoint path.
        max_turns: Maximum agentic loop iterations before giving up.
    """

    def __init__(
        self,
        model_id: str = DEFAULT_MODEL_ID,
        max_turns: int = DEFAULT_MAX_TURNS,
        load_in_8bit: bool = True,
    ) -> None:
        self.model_id = model_id
        self.max_turns = max_turns
        self.load_in_8bit = load_in_8bit
        self._model: Any = None
        self._processor: Any = None

    # ------------------------------------------------------------------
    # Lazy loading
    # ------------------------------------------------------------------

    def _load(self) -> None:
        """Download and initialise Qwen2-VL weights (idempotent).

        Raises:
            ImportError: If ``transformers>=4.45.0`` is not installed.
        """
        if self._model is not None:
            return
        try:
            from transformers import AutoProcessor, BitsAndBytesConfig, Qwen2_5_VLForConditionalGeneration
        except ImportError as exc:
            raise ImportError(
                "transformers>=4.45.0 is required for Qwen2.5-VL support.\n"
                "Run: pip install 'transformers>=4.45.0'"
            ) from exc
        quant_config = BitsAndBytesConfig(load_in_8bit=True) if self.load_in_8bit else None
        logger.info(
            "Loading DeepEyesV2 from '%s' (8-bit=%s) …", self.model_id, self.load_in_8bit
        )
        self._model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            self.model_id,
            torch_dtype="auto",
            device_map="auto",
            quantization_config=quant_config,
        )
        # Cap visual tokens: 1280×28×28 ≈ 1M pixels → ~256 visual tokens max.
        # Without this, high-res images create thousands of tokens per turn.
        self._processor = AutoProcessor.from_pretrained(
            self.model_id,
            min_pixels=256 * 28 * 28,
            max_pixels=1280 * 28 * 28,
        )
        logger.info("DeepEyesV2 loaded.")

    # ------------------------------------------------------------------
    # BaseVisualCoTModel interface
    # ------------------------------------------------------------------

    def generate(
        self,
        image: Image.Image,
        query: str,
        *,
        n: int = 1,
        temperature: float = 0.2,
        max_new_tokens: int = 512,
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:
        """Run *n* independent agentic chains and return their chain dicts.

        Args:
            image: Input PIL image.
            query: Question / instruction string.
            n: Number of independent samples to draw.
            temperature: Sampling temperature (0 = greedy).
            max_new_tokens: Token budget per generation turn.
            **kwargs: Ignored (reserved for future use).

        Returns:
            List of *n* chain dicts, each with keys:
            ``"bbox_raw"`` (``None``), ``"coords"`` (``[]``),
            ``"answer"`` (str), ``"cot_steps"`` (list[str]),
            ``"tool_results"`` (list[str]).
        """
        self._load()
        return [
            self._run_chain(image, query, temperature, max_new_tokens)
            for _ in range(n)
        ]

    # ------------------------------------------------------------------
    # Internal: agentic loop
    # ------------------------------------------------------------------

    def _run_chain(
        self,
        image: Image.Image,
        query: str,
        temperature: float,
        max_new_tokens: int,
    ) -> Dict[str, Any]:
        """Run a single multi-turn agentic chain.

        Args:
            image: Input PIL image.
            query: User question.
            temperature: Sampling temperature.
            max_new_tokens: Token budget per turn.

        Returns:
            Chain dict with keys ``bbox_raw``, ``coords``, ``answer``,
            ``cot_steps``, ``tool_results``.
        """
        import numpy as np
        import PIL

        # Build code-execution namespace matching the training environment:
        # image_i is a PIL Image (opened via PIL.Image.open()), NOT a NumPy array.
        # The model writes code like image_1.crop(...) / image_1.resize(...).
        # Also expose `image` as an alias — the model sometimes omits the `_1` suffix.
        pil_image = image.convert("RGB")
        exec_ns: Dict[str, Any] = {
            "np": np,
            "PIL": PIL,
            "image_1": pil_image,
            "image": pil_image,       # alias: model may write `image` instead of `image_1`
            "math": __import__("math"),
            "collections": __import__("collections"),
        }

        # Encode image as base64 PNG data URI (safe, no temp files).
        buf = io.BytesIO()
        image.convert("RGB").save(buf, format="PNG")
        b64 = base64.b64encode(buf.getvalue()).decode()
        image_uri = f"data:image;base64,{b64}"

        # Wrap the query in the exact USER_PROMPT_TEMPLATE from the paper.
        # This is what tells the model to use <answer> tags and the strict format.
        formatted_query = USER_PROMPT_TEMPLATE.format(question=query)

        messages: List[Dict[str, Any]] = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image_uri},
                    {"type": "text", "text": formatted_query},
                ],
            },
        ]

        cot_steps: List[str] = []
        tool_results: List[str] = []
        final_answer: str = ""

        for _ in range(self.max_turns):
            response = self._call_model(messages, temperature, max_new_tokens)
            cot_steps.append(response)

            # Check for termination first.
            answer = _parse_answer(response)
            if answer is not None:
                final_answer = answer
                break

            # Check for code execution request.
            code = _extract_code_block(response)
            if code is not None:
                tool_output = _execute_code(code, exec_ns)
                tool_results.append(tool_output)
                messages.append({"role": "assistant", "content": response})
                # Inject tool result using the exact RETURN_CODE_USER_PROMPT from the paper.
                tool_msg = RETURN_CODE_USER_PROMPT.format(
                    stdout=tool_output, stderr=""
                )
                messages.append({"role": "user", "content": tool_msg})
            else:
                # Neither <code> nor <answer>: treat entire response as answer.
                final_answer = response
                break

        return {
            "bbox_raw": None,
            "coords": [],
            "answer": final_answer,
            "cot_steps": cot_steps,
            "tool_results": tool_results,
        }

    # ------------------------------------------------------------------
    # Internal: single HF generation call
    # ------------------------------------------------------------------

    def _call_model(
        self,
        messages: List[Dict[str, Any]],
        temperature: float,
        max_new_tokens: int,
    ) -> str:
        """Run one forward pass and return the decoded response string.

        Args:
            messages: OpenAI-style conversation history.
            temperature: Sampling temperature.
            max_new_tokens: Maximum tokens to generate.

        Returns:
            Decoded model output (prompt tokens stripped).
        """
        from qwen_vl_utils import process_vision_info

        text = self._processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        image_inputs, video_inputs = process_vision_info(messages)
        inputs = self._processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        ).to(self._model.device)

        generate_kwargs: Dict[str, Any] = {
            "max_new_tokens": max_new_tokens,
            "use_cache": True,
            # Match the model's generation_config.json (prevents repetition loops).
            "repetition_penalty": 1.05,
        }
        if temperature > 0.0:
            generate_kwargs["do_sample"] = True
            generate_kwargs["temperature"] = temperature
        else:
            generate_kwargs["do_sample"] = False

        with torch.inference_mode():
            out_ids = self._model.generate(**inputs, **generate_kwargs)

        # Trim the prompt tokens from the output.
        prompt_len = inputs["input_ids"].shape[1]
        trimmed = out_ids[:, prompt_len:]
        result = self._processor.batch_decode(
            trimmed,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        )[0].strip()

        # Free GPU tensors immediately — without this every agentic turn leaks
        # the input allocation, causing VRAM to fill up across turns.
        del inputs, out_ids, trimmed
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        return result
