"""DeepEyesV2 model wrapper — Qwen2.5-VL with agentic tool-use CoT.

DeepEyesV2 (honglyhly/DeepEyesV2_7B_1031) is a Qwen2.5-VL-7B model
fine-tuned via SFT + GRPO reinforcement learning to perform multi-turn
reasoning using a Python code-execution tool.

The model's reasoning loop:
1. Receives system prompt + image + user query.
2. Optionally executes Python code (``<code>...</code>``) to inspect the image.
3. Repeats until it emits ``<answer>...</answer>``, which terminates the loop.

This module exposes:
- :class:`DeepEyesV2Model` — ``BaseVisualCoTModel`` implementation.
- :func:`_parse_answer` — extract ``<answer>`` tag content.
- :func:`_extract_code_block` — extract ``<code>`` tag content.
- :func:`_execute_code` — run Python code with an isolated namespace,
  returning ``(stdout, stderr, figure_bytes)``.
"""

from __future__ import annotations

import base64
import contextlib
import io
import json
import os
import re
import textwrap
from typing import Any, Dict, List, Optional, Tuple

# Force a non-interactive matplotlib backend before any user code can import
# matplotlib.  Without this, plt.show() inside the code sandbox opens a GUI
# window and blocks execution indefinitely.
os.environ.setdefault("MPLBACKEND", "Agg")

from PIL import Image

from src.models.base import BaseVisualCoTModel
from src.utils.logging import get_logger
from src.utils_normalize import normalize_answer

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_MODEL_ID = "honglyhly/DeepEyesV2_7B_1031"
DEFAULT_MAX_TURNS = 10

# ---------------------------------------------------------------------------
# Exact prompts from the paper (Appendix A.8 of arXiv:2511.05271).
# Search-tool instructions are omitted; only the Python-code tool is kept.
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are an agent - please keep going until the user's query is completely resolved, before ending your turn and yielding back to the user. Only terminate your turn when you are sure that the problem is solved.

Solve the following problem step by step. In your reasoning process, if the answer cannot be determined, you can write Python code in a Jupyter Notebook to process the image and extract more information from it. The stdout and stderr content, along with the images generated by `plt.show()` will be returned to better assist with the user query.

You MUST use the python tool to analyze or transform images whenever it could improve your understanding. This includes but is not limited to zooming in, rotating, adjusting contrast, computing statistics, or isolating features.

You MUST plan extensively before each function call, and reflect extensively on the outcomes of the previous function calls. DO NOT do this entire process by making function calls only, as this can impair your ability to solve the problem and think insightfully.

For all the provided images, in order, the i-th image has already been read into the global variable "image_i" using the "PIL.Image.open()" function. When writing Python code, you can directly use these variables without needing to read them again.

## Tools

## python
Your python code should be enclosed within <code> </code> tag.

Example for calling Python code in Jupyter Notebook:
<code>
```python
# python code here
```
</code>

Note:
1. **python** can be called to analyze the image. **python** will respond with the output of the execution or time out after 300.0 seconds.
2. Like jupyter notebook, you can use Python code to process the input image and use `plt.show()` to visualize processed images in your code.
3. All python code are running in the same jupyter notebook kernel, which means the functions and variables are automatically stored after code execution.
4. You program should always returns in finite time. Do not write infinite loop in your code.
5. Writing file to disk is not allowed.
"""

# USER_PROMPT_TEMPLATE: wraps each user query.
# Matches training data format from inference_demo.py (including "neededs" typo).
# <image> placeholder is omitted — the HuggingFace processor inserts vision tokens
# automatically from the content items; no manual placement needed.
USER_PROMPT_TEMPLATE = """\
{question}

You must put your answer inside <answer> </answer> tags, i.e., <answer> answer here </answer>. Please reason step by step. Use Python code to process the image if necessary. You can conduct search to seek the Internet. Format strictly as <think> </think> <code> </code> (if code is neededs) or <think> </think> <tool_call> </tool_call> (if function call is neededs) or <think> <think> <answer> </answer>."""

# RETURN_CODE_USER_PROMPT: injected after each code execution.
# Matches RETURN_PROMPT from inference_demo.py exactly.
# {image} is filled dynamically: "Images:\n<image><image>..." when figures exist,
# empty string otherwise.
RETURN_CODE_USER_PROMPT = """\
Code execution result:
stdout:
```
{stdout}
```

stderr:
```
{stderr}
```

{image}"""

# RETURN_SEARCH_PROMPT: injected when the model calls a search tool.
# We stub it with a no-internet message wrapped in the training format.
RETURN_SEARCH_PROMPT = """\
<tool_response>
No internet access available. Please answer based on the image alone.
</tool_response>"""

# ---------------------------------------------------------------------------
# Module-level helpers (public for testability)
# ---------------------------------------------------------------------------

_ANSWER_RE = re.compile(r"<answer>(.*?)</answer>", re.DOTALL)
_CODE_RE = re.compile(r"<code>(.*?)</code>", re.DOTALL)
_TOOL_CALL_RE = re.compile(r"<tool_call>(.*?)</tool_call>", re.DOTALL)
# Matches the '''python ... ''' wrapper the model places inside <code> tags.
_PYTHON_TRIPLE_QUOTE_RE = re.compile(r"^\s*'''python\s*\n(.*?)\n\s*'''\s*$", re.DOTALL)
# Backtick fence *inside* a <code> tag: ```python ... ```
_BACKTICK_FENCE_RE = re.compile(r"^\s*```python\s*\n(.*?)\n\s*```\s*$", re.DOTALL)
# Top-level bare backtick fence (model output without <code> wrapper).
_BARE_FENCE_RE = re.compile(r"```python\s*\n(.*?)\n```", re.DOTALL)


def _parse_answer(text: str) -> Optional[str]:
    """Extract the first ``<answer>...</answer>`` span, stripped, or ``None``.

    Args:
        text: Raw model output string.

    Returns:
        Stripped answer text, or ``None`` if no ``<answer>`` tag is found.
    """
    m = _ANSWER_RE.search(text)
    return m.group(1).strip() if m else None


def _extract_code_block(text: str) -> Optional[str]:
    """Extract the **last** ``<code>...</code>`` span, stripping any Python markdown wrapper.

    Uses the last match (not first) because the model sometimes revises its code
    inline, emitting multiple ``<code>`` blocks in one turn — the final block is
    the intended one to execute (mirrors ``extract_python_code`` in inference_demo.py).

    Args:
        text: Raw model output string.

    Returns:
        Executable Python source (indentation preserved), or ``None`` if no tag found.
    """
    # Priority 1: explicit <code>...</code> tags (training format) — take last.
    matches = _CODE_RE.findall(text)
    if matches:
        raw = matches[-1]
        for pattern in (_PYTHON_TRIPLE_QUOTE_RE, _BACKTICK_FENCE_RE):
            wrapper_m = pattern.match(raw)
            if wrapper_m:
                return wrapper_m.group(1)
        return raw
    # Priority 2: bare ```python ... ``` fence — take last.
    bare_matches = _BARE_FENCE_RE.findall(text)
    if bare_matches:
        return bare_matches[-1]
    return None


def _extract_tool_call(text: str) -> Optional[Dict[str, Any]]:
    """Extract and JSON-parse the **last** ``<tool_call>...</tool_call>`` block.

    The model emits search calls in this format::

        <tool_call>{"name": "search", "arguments": {"query": "..."}}</tool_call>
        <tool_call>{"name": "image_search"}</tool_call>

    Args:
        text: Raw model output string.

    Returns:
        Parsed dict with at least ``"name"`` key, or ``None`` if no tag or invalid JSON.
    """
    matches = _TOOL_CALL_RE.findall(text)
    if not matches:
        return None
    try:
        return json.loads(matches[-1].strip())
    except (json.JSONDecodeError, ValueError):
        return None


def _fix_python_indentation(code: str) -> str:
    """Best-effort indentation normalizer for model-generated Python code.

    Model output often carries a uniform leading indent (e.g. the code was
    inside a fenced block that was itself indented).  ``textwrap.dedent``
    removes that common prefix so ``exec()`` does not raise ``IndentationError``.

    Args:
        code: Raw Python source, possibly over-indented.

    Returns:
        Dedented and stripped source, or the original string if dedent fails.
    """
    try:
        return textwrap.dedent(code).strip()
    except Exception:
        return code


def _execute_code(
    code: str, namespace: Dict[str, Any]
) -> Tuple[str, str, List[bytes]]:
    """Execute *code* in *namespace* and return stdout, stderr, and any matplotlib figures.

    Intercepts ``plt.show()`` calls to capture the current figure as PNG bytes
    instead of attempting to open a display.  The namespace is modified in-place
    so variables persist across multi-turn calls.

    Args:
        code: Python source code to execute.
        namespace: Execution namespace; modified in-place by the code.

    Returns:
        A 3-tuple of:
        - ``stdout`` — captured print output (trailing newlines stripped).
        - ``stderr`` — exception summary ``"ExcType: message"``, or ``""`` on success.
        - ``figures`` — list of PNG-encoded bytes for each ``plt.show()`` call.
    """
    buf = io.StringIO()
    figures: List[bytes] = []

    # Intercept plt.show() so figures are captured rather than displayed.
    orig_show = None
    try:
        import matplotlib.pyplot as _plt

        orig_show = _plt.show

        def _capture_show(*args: Any, **kwargs: Any) -> None:
            fig_buf = io.BytesIO()
            _plt.savefig(fig_buf, format="png", bbox_inches="tight", dpi=100)
            fig_buf.seek(0)
            figures.append(fig_buf.getvalue())
            _plt.close("all")

        _plt.show = _capture_show
    except ImportError:
        pass  # matplotlib not installed — plt.show() calls will raise inside exec

    try:
        with contextlib.redirect_stdout(buf):
            exec(code, namespace)  # noqa: S102
        return buf.getvalue().rstrip("\n"), "", figures
    except Exception as exc:  # noqa: BLE001
        return buf.getvalue().rstrip("\n"), f"{type(exc).__name__}: {exc}", figures
    finally:
        if orig_show is not None:
            import matplotlib.pyplot as _plt
            _plt.show = orig_show


# ---------------------------------------------------------------------------
# Model class
# ---------------------------------------------------------------------------


class DeepEyesV2Model(BaseVisualCoTModel):
    """Multi-turn agentic Visual CoT model backed by DeepEyesV2 / Qwen2.5-VL.

    Loads ``Qwen2_5_VLForConditionalGeneration`` weights lazily on the first
    :meth:`generate` call (no download at import time).

    Args:
        model_id: HuggingFace model ID or local checkpoint path.
        max_turns: Maximum agentic loop iterations before giving up.
        load_in_8bit: Whether to quantise weights to 8-bit with BitsAndBytes.
    """

    def __init__(
        self,
        model_id: str = DEFAULT_MODEL_ID,
        max_turns: int = DEFAULT_MAX_TURNS,
        load_in_8bit: bool = True,
    ) -> None:
        self.model_id = model_id
        self.max_turns = max_turns
        self.load_in_8bit = load_in_8bit
        self._model: Any = None
        self._processor: Any = None

    # ------------------------------------------------------------------
    # Lazy loading
    # ------------------------------------------------------------------

    def _load(self) -> None:
        """Download and initialise Qwen2.5-VL weights (idempotent).

        Raises:
            ImportError: If ``transformers>=4.45.0`` is not installed.
        """
        if self._model is not None:
            return
        try:
            from transformers import AutoProcessor, BitsAndBytesConfig, Qwen2_5_VLForConditionalGeneration
        except ImportError as exc:
            raise ImportError(
                "transformers>=4.45.0 is required for Qwen2.5-VL support.\n"
                "Run: pip install 'transformers>=4.45.0'"
            ) from exc
        quant_config = BitsAndBytesConfig(load_in_8bit=True) if self.load_in_8bit else None
        logger.info(
            "Loading DeepEyesV2 from '%s' (8-bit=%s) …", self.model_id, self.load_in_8bit
        )
        self._model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            self.model_id,
            torch_dtype="auto",
            device_map="auto",
            quantization_config=quant_config,
        )
        # Match inference_demo.py: MIN_PIXELS = 4*28*28, MAX_PIXELS = 16384*28*28.
        self._processor = AutoProcessor.from_pretrained(
            self.model_id,
            min_pixels=4 * 28 * 28,
            max_pixels=16384 * 28 * 28,
        )
        import torch as _torch
        self._torch = _torch
        logger.info("DeepEyesV2 loaded.")

    # ------------------------------------------------------------------
    # BaseVisualCoTModel interface
    # ------------------------------------------------------------------

    def generate(
        self,
        image: Image.Image,
        query: str,
        *,
        n: int = 1,
        temperature: float = 0.0,
        max_new_tokens: int = 20480,
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:
        """Run *n* independent agentic chains and return their chain dicts.

        Args:
            image: Input PIL image.
            query: Question / instruction string.
            n: Number of independent samples to draw.
            temperature: Sampling temperature (0 = greedy).
            max_new_tokens: Token budget per generation turn.  Defaults to 20480
                to match the original inference_demo.py.  A full ``<think>`` +
                ``<code>`` + multi-turn trace can easily exceed 8k tokens; using
                less than ~4096 risks truncating CoT mid-block.
            **kwargs: Ignored (reserved for future use).

        Returns:
            List of *n* chain dicts, each with keys:
            ``"bbox_raw"`` (``None``), ``"coords"`` (``[]``),
            ``"answer"`` (str), ``"cot_steps"`` (list[str]),
            ``"tool_results"`` (list[str]).
        """
        self._load()
        return [
            self._run_chain(image, query, temperature, max_new_tokens)
            for _ in range(n)
        ]

    # ------------------------------------------------------------------
    # Internal: agentic loop
    # ------------------------------------------------------------------

    def _run_chain(
        self,
        image: Image.Image,
        query: str,
        temperature: float,
        max_new_tokens: int,
    ) -> Dict[str, Any]:
        """Run a single multi-turn agentic chain.

        Args:
            image: Input PIL image.
            query: User question.
            temperature: Sampling temperature.
            max_new_tokens: Token budget per turn.

        Returns:
            Chain dict with keys ``bbox_raw``, ``coords``, ``answer``,
            ``cot_steps``, ``tool_results``.
        """
        import numpy as np
        import PIL

        # Build code-execution namespace matching the training environment.
        # image_i is a PIL Image (matching PIL.Image.open() semantics in the system prompt).
        # `image` is provided as an alias — the model occasionally omits the `_1` suffix.
        pil_image = image.convert("RGB")
        exec_ns: Dict[str, Any] = {
            "np": np,
            "PIL": PIL,
            "image_1": pil_image,
            "image": pil_image,
            "math": __import__("math"),
            "collections": __import__("collections"),
        }

        # Encode image as base64 PNG data URI (safe, no temp files).
        buf = io.BytesIO()
        pil_image.save(buf, format="PNG")
        b64 = base64.b64encode(buf.getvalue()).decode()
        image_uri = f"data:image/png;base64,{b64}"

        # Wrap the query in USER_PROMPT_TEMPLATE — instructs model to use <answer> tags.
        formatted_query = USER_PROMPT_TEMPLATE.format(question=query)

        messages: List[Dict[str, Any]] = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image_uri},
                    {"type": "text", "text": formatted_query},
                ],
            },
        ]

        cot_steps: List[str] = []
        tool_results: List[str] = []
        final_answer: str = ""

        for _ in range(self.max_turns):
            response = self._call_model(messages, temperature, max_new_tokens)
            cot_steps.append(response)

            # Check for termination first.
            answer = _parse_answer(response)
            if answer is not None:
                final_answer = answer
                break

            # Check for search/internet tool call — stub it out, no network access.
            # The model emits: <tool_call>{"name": "search", "arguments": {...}}</tool_call>
            tool_call = _extract_tool_call(response)
            if tool_call is not None:
                stub = RETURN_SEARCH_PROMPT
                tool_results.append(stub)
                messages.append({"role": "assistant", "content": response})
                messages.append({
                    "role": "user",
                    "content": [{"type": "text", "text": stub}],
                })
                continue

            # Check for code execution request.
            code = _extract_code_block(response)
            if code is not None:
                code = _fix_python_indentation(code)
                stdout, stderr, figures = _execute_code(code, exec_ns)
                tool_results.append(stderr if stderr else stdout)

                # Build the tool-result user message.
                # image_placeholder matches the training format: "Images:\n<image><image>..."
                # where each <image> marker corresponds to one injected vision token.
                image_placeholder = (
                    "Images:\n" + "<image>" * len(figures) if figures else ""
                )
                tool_text = RETURN_CODE_USER_PROMPT.format(
                    stdout=stdout, stderr=stderr, image=image_placeholder
                ).strip()
                tool_content: List[Dict[str, Any]] = [{"type": "text", "text": tool_text}]
                for fig_bytes in figures:
                    fig_b64 = base64.b64encode(fig_bytes).decode()
                    fig_uri = f"data:image/png;base64,{fig_b64}"
                    tool_content.append({"type": "image", "image": fig_uri})

                messages.append({"role": "assistant", "content": response})
                messages.append({"role": "user", "content": tool_content})
            else:
                # Neither <code> nor <answer>: the model may have reasoned to a conclusion
                # without using the tag, or the output was truncated.  Attempt to salvage
                # a normalized answer before falling back to the raw response.
                salvaged = normalize_answer(response)
                final_answer = salvaged if salvaged is not None else response
                break

        return {
            "bbox_raw": None,
            "coords": [],
            "answer": final_answer,
            "cot_steps": cot_steps,
            "tool_results": tool_results,
        }

    # ------------------------------------------------------------------
    # Internal: single HF generation call
    # ------------------------------------------------------------------

    def _call_model(
        self,
        messages: List[Dict[str, Any]],
        temperature: float,
        max_new_tokens: int,
    ) -> str:
        """Run one forward pass and return the decoded response string.

        Args:
            messages: OpenAI-style conversation history.
            temperature: Sampling temperature.
            max_new_tokens: Maximum tokens to generate.

        Returns:
            Decoded model output (prompt tokens stripped).
        """
        from qwen_vl_utils import process_vision_info

        text = self._processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        image_inputs, video_inputs = process_vision_info(messages)
        inputs = self._processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        ).to(self._model.device)

        generate_kwargs: Dict[str, Any] = {
            "max_new_tokens": max_new_tokens,
            "use_cache": True,
            # Match the model's generation_config.json (prevents repetition loops).
            "repetition_penalty": 1.05,
        }
        if temperature > 0.0:
            generate_kwargs["do_sample"] = True
            generate_kwargs["temperature"] = temperature
        else:
            generate_kwargs["do_sample"] = False

        torch = self._torch
        with torch.inference_mode():
            out_ids = self._model.generate(**inputs, **generate_kwargs)

        # Trim the prompt tokens from the output.
        prompt_len = inputs["input_ids"].shape[1]
        trimmed = out_ids[:, prompt_len:]
        result = self._processor.batch_decode(
            trimmed,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        )[0].strip()

        # Free GPU tensors immediately — without this every agentic turn leaks
        # the input allocation, causing VRAM to fill up across turns.
        del inputs, out_ids, trimmed
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        return result
